### ISSUE TITLE
Can't Register

### ISSUE THREAD

**Issue by DeMoN100** [Supertigerr/nertivia-client-ts#63]
Could you remove your block on every email provider except gmail so not just me but anyone could try this out? If not at least unblock proton one of the most secure emails thats known.

**Comment by Supertigerr** [comment]
Hello, I think that is a bug. It says "Non gmail emails have been blacklisted for a day." Even though no one has registered yet. I will check this out, thanks.

**Comment by DeMoN100** [comment]
> Hello, I think that is a bug. It says "Non gmail emails have been blacklisted for a day." Even though no one has registered yet. I will check this out, thanks.

Yes I am unabke to register because of this. Thats probably why nobody could register at all.

**Comment by Supertigerr** [comment]
Does it exactly say "Non gmail emails have been blacklisted for a day." or is it something else?

**Comment by DeMoN100** [comment]
Thank you for fixing. I am now in your server!
